apiVersion: v2
name: crossplane-argocd
description: A Helm chart for deploying core Crossplane.
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: crossplane
    version: 1.6.1
    repository: https://charts.crossplane.io/stable
